/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/video-projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Video Projects */
        get: operations["list_video_projects_api_v1_video_projects_get"];
        put?: never;
        /** Create Video Project */
        post: operations["create_video_project_api_v1_video_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video Project */
        get: operations["get_video_project_api_v1_video_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Video Project */
        delete: operations["delete_video_project_api_v1_video_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Patch Video Project */
        patch: operations["patch_video_project_api_v1_video_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/start-workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Workflow */
        post: operations["start_workflow_api_v1_video_projects__project_id__start_workflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/request-approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Approval */
        post: operations["request_approval_api_v1_video_projects__project_id__request_approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_api_v1_video_projects__project_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject */
        post: operations["reject_api_v1_video_projects__project_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/needs-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Needs Changes */
        post: operations["needs_changes_api_v1_video_projects__project_id__needs_changes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval */
        get: operations["approval_api_v1_video_projects__project_id__approval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/approval-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Approval Decisions */
        get: operations["approval_decisions_api_v1_video_projects__project_id__approval_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_video_projects__project_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Costs */
        get: operations["costs_api_v1_video_projects__project_id__costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quota */
        get: operations["quota_api_v1_video_projects__project_id__quota_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/compliance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compliance */
        get: operations["compliance_api_v1_video_projects__project_id__compliance_get"];
        put?: never;
        /** Run Compliance */
        post: operations["run_compliance_api_v1_video_projects__project_id__compliance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/{project_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Analytics */
        get: operations["analytics_api_v1_video_projects__project_id__analytics_get"];
        put?: never;
        /** Create Analytics Snapshot */
        post: operations["create_analytics_snapshot_api_v1_video_projects__project_id__analytics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/publishing-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Publishing Plan */
        post: operations["create_publishing_plan_api_v1_video_projects_publishing_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/publishing-plans/{plan_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Publishing */
        post: operations["schedule_publishing_api_v1_video_projects_publishing_plans__plan_id__schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/video-projects/publishing-plans/{plan_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Video */
        post: operations["publish_video_api_v1_video_projects_publishing_plans__plan_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Channels */
        get: operations["list_channels_api_v1_channels_get"];
        put?: never;
        /** Create Channel */
        post: operations["create_channel_api_v1_channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel */
        get: operations["get_channel_api_v1_channels__channel_id__get"];
        put?: never;
        post?: never;
        /** Delete Channel */
        delete: operations["delete_channel_api_v1_channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Patch Channel */
        patch: operations["patch_channel_api_v1_channels__channel_id__patch"];
        trace?: never;
    };
    "/api/v1/channels/{channel_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Channel Memory */
        get: operations["get_channel_memory_api_v1_channels__channel_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Channel Memory */
        patch: operations["patch_channel_memory_api_v1_channels__channel_id__memory_patch"];
        trace?: never;
    };
    "/api/v1/usage/{organization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_api_v1_usage__organization_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage/{organization_id}/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Channel */
        post: operations["register_channel_api_v1_usage__organization_id__channels__channel_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsSnapshotIn */
        AnalyticsSnapshotIn: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Youtube Video Id */
            youtube_video_id: string;
            /** Views */
            views: number;
            /** Watch Time Minutes */
            watch_time_minutes: number;
            /** Average View Duration */
            average_view_duration: number;
            /** Ctr */
            ctr: number;
            /** Likes */
            likes: number;
            /** Comments */
            comments: number;
            /** Subscribers Gained */
            subscribers_gained: number;
            /** Estimated Revenue */
            estimated_revenue: number;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
        };
        /** AnalyticsSnapshotOut */
        AnalyticsSnapshotOut: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Youtube Video Id */
            youtube_video_id: string;
            /** Views */
            views: number;
            /** Watch Time Minutes */
            watch_time_minutes: number;
            /** Average View Duration */
            average_view_duration: number;
            /** Ctr */
            ctr: number;
            /** Likes */
            likes: number;
            /** Comments */
            comments: number;
            /** Subscribers Gained */
            subscribers_gained: number;
            /** Estimated Revenue */
            estimated_revenue: number;
            /**
             * Snapshot At
             * Format: date-time
             */
            snapshot_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Project Id
             * Format: uuid
             */
            video_project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ApprovalAggregateOut */
        ApprovalAggregateOut: {
            /**
             * Video Project Id
             * Format: uuid
             */
            video_project_id: string;
            /** Status */
            status: string;
            /** Requested At */
            requested_at?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Decided By User Id */
            decided_by_user_id?: string | null;
            /** Latest Comment */
            latest_comment?: string | null;
        };
        /** ApprovalDecisionIn */
        ApprovalDecisionIn: {
            /** Comment */
            comment?: string | null;
            /**
             * Decided By User Id
             * Format: uuid
             */
            decided_by_user_id: string;
        };
        /** ApprovalDecisionOut */
        ApprovalDecisionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Project Id
             * Format: uuid
             */
            video_project_id: string;
            /** Status */
            status: string;
            /** Comment */
            comment?: string | null;
            /**
             * Decided By User Id
             * Format: uuid
             */
            decided_by_user_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChannelCreate */
        ChannelCreate: {
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Name */
            name: string;
            /** Youtube Channel Id */
            youtube_channel_id: string;
        };
        /** ChannelMemoryOut */
        ChannelMemoryOut: {
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            memory?: components["schemas"]["ChannelMemoryPayload"];
        };
        /** ChannelMemoryPayload */
        ChannelMemoryPayload: {
            /** Approved Title Patterns */
            approved_title_patterns?: string[];
            /** Rejected Title Patterns */
            rejected_title_patterns?: string[];
            /** Thumbnail Rules */
            thumbnail_rules?: {
                [key: string]: unknown;
            };
            /** Banned Phrases */
            banned_phrases?: string[];
            /** Preferred Phrases */
            preferred_phrases?: string[];
            /** Compliance Preferences */
            compliance_preferences?: {
                [key: string]: unknown;
            };
            /** Narrator Style */
            narrator_style?: {
                [key: string]: unknown;
            };
            /** Visual Style */
            visual_style?: {
                [key: string]: unknown;
            };
            /** Audience Objections */
            audience_objections?: string[];
            /** Best Performing Patterns */
            best_performing_patterns?: string[];
            /** Worst Performing Patterns */
            worst_performing_patterns?: string[];
            /** Freeform Memory Notes */
            freeform_memory_notes?: string[];
        };
        /** ChannelOut */
        ChannelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Name */
            name: string;
            /** Youtube Channel Id */
            youtube_channel_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Name */
            name?: string | null;
            /** Youtube Channel Id */
            youtube_channel_id?: string | null;
        };
        /** ComplianceReportOut */
        ComplianceReportOut: {
            /**
             * Video Project Id
             * Format: uuid
             */
            video_project_id: string;
            /** Score */
            score: number;
            risk_level: components["schemas"]["ComplianceRiskLevel"];
            /** Requires Ai Disclosure */
            requires_ai_disclosure: boolean;
            /** Disclosure Decision Missing */
            disclosure_decision_missing: boolean;
            /** Ai Disclosure Risk */
            ai_disclosure_risk: string;
            /** Inauthentic Content Risk */
            inauthentic_content_risk: string;
            /** Repetitive Content Risk */
            repetitive_content_risk: string;
            /** Copyright Risk */
            copyright_risk: string;
            /** Sensitive Claims Risk */
            sensitive_claims_risk: string;
            /** Clickbait Risk */
            clickbait_risk: string;
            /** Asset License Risk */
            asset_license_risk: string;
            /** Synthetic Media Realism Risk */
            synthetic_media_realism_risk: string;
            /** Reasons */
            reasons: string[];
            /** Recommendations */
            recommendations: string[];
            /** Blocking Issues */
            blocking_issues: string[];
        };
        /**
         * ComplianceRiskLevel
         * @enum {string}
         */
        ComplianceRiskLevel: "low" | "medium" | "high" | "blocked";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedChannels */
        PaginatedChannels: {
            /** Items */
            items: components["schemas"]["ChannelOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PaginatedVideoProjects */
        PaginatedVideoProjects: {
            /** Items */
            items: components["schemas"]["VideoProjectOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PublishingPlanCreate */
        PublishingPlanCreate: {
            /**
             * Video Project Id
             * Format: uuid
             */
            video_project_id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Tags */
            tags?: string[];
            /**
             * Visibility
             * @default private
             */
            visibility: string;
            /** Selected Title Variant Id */
            selected_title_variant_id?: string | null;
            /** Selected Thumbnail Concept Id */
            selected_thumbnail_concept_id?: string | null;
            /** Final Description Snapshot */
            final_description_snapshot?: string | null;
            /** Final Tags Snapshot */
            final_tags_snapshot?: string[] | null;
            /** Compliance Report Id */
            compliance_report_id?: string | null;
            /** Asset Bundle Metadata */
            asset_bundle_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** PublishingPlanOut */
        PublishingPlanOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Video Project Id
             * Format: uuid
             */
            video_project_id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Scheduled At */
            scheduled_at: string | null;
            status: components["schemas"]["PublishingPlanStatus"];
            /** Youtube Video Id */
            youtube_video_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Tags */
            tags: string[];
            /** Visibility */
            visibility: string;
            /** Selected Title Variant Id */
            selected_title_variant_id?: string | null;
            /** Selected Thumbnail Concept Id */
            selected_thumbnail_concept_id?: string | null;
            /** Final Description Snapshot */
            final_description_snapshot?: string | null;
            /** Final Tags Snapshot */
            final_tags_snapshot?: string[] | null;
            /** Compliance Report Id */
            compliance_report_id?: string | null;
            /** Asset Bundle Metadata */
            asset_bundle_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PublishingPlanSchedule */
        PublishingPlanSchedule: {
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
        };
        /**
         * PublishingPlanStatus
         * @enum {string}
         */
        PublishingPlanStatus: "draft" | "scheduled" | "uploading" | "published" | "failed" | "cancelled";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoProjectCreate */
        VideoProjectCreate: {
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
        };
        /** VideoProjectOut */
        VideoProjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Channel Id
             * Format: uuid
             */
            channel_id: string;
            /** Title */
            title: string;
            status: components["schemas"]["VideoProjectStatus"];
            approval?: components["schemas"]["ApprovalAggregateOut"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VideoProjectStatus
         * @enum {string}
         */
        VideoProjectStatus: "draft" | "researching" | "script_generating" | "seo_generating" | "compliance_checking" | "awaiting_review" | "approved" | "rejected" | "needs_changes" | "scheduled" | "published" | "analytics_pending" | "completed" | "failed" | "cancelled";
        /** VideoProjectUpdate */
        VideoProjectUpdate: {
            /** Title */
            title?: string | null;
            status?: components["schemas"]["VideoProjectStatus"] | null;
        };
        /** WorkflowEventOut */
        WorkflowEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workflow Run Id
             * Format: uuid
             */
            workflow_run_id: string;
            /** Event Type */
            event_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_video_projects_api_v1_video_projects_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["VideoProjectStatus"] | null;
                channel_id?: string | null;
                workspace_id?: string | null;
            };
            header?: {
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
                "x-correlation-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVideoProjects"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_video_project_api_v1_video_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_project_api_v1_video_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_project_api_v1_video_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_video_project_api_v1_video_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workflow_api_v1_video_projects__project_id__start_workflow_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_approval_api_v1_video_projects__project_id__request_approval_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_video_projects__project_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_video_projects__project_id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    needs_changes_api_v1_video_projects__project_id__needs_changes_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_api_v1_video_projects__project_id__approval_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalAggregateOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approval_decisions_api_v1_video_projects__project_id__approval_decisions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalDecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_video_projects__project_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    costs_api_v1_video_projects__project_id__costs_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quota_api_v1_video_projects__project_id__quota_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compliance_api_v1_video_projects__project_id__compliance_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_compliance_api_v1_video_projects__project_id__compliance_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplianceReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_api_v1_video_projects__project_id__analytics_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analytics_snapshot_api_v1_video_projects__project_id__analytics_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsSnapshotIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSnapshotOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_publishing_plan_api_v1_video_projects_publishing_plans_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishingPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_publishing_api_v1_video_projects_publishing_plans__plan_id__schedule_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishingPlanSchedule"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_video_api_v1_video_projects_publishing_plans__plan_id__publish_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishingPlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_v1_channels_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
                "x-correlation-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChannels"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_api_v1_channels_post: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_api_v1_channels__channel_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_v1_channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_channel_api_v1_channels__channel_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_channel_memory_api_v1_channels__channel_id__memory_get: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMemoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_channel_memory_api_v1_channels__channel_id__memory_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-correlation-id"?: string | null;
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
            };
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelMemoryPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelMemoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_api_v1_usage__organization_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
                "x-correlation-id"?: string | null;
            };
            path: {
                organization_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_channel_api_v1_usage__organization_id__channels__channel_id__post: {
        parameters: {
            query?: never;
            header?: {
                "X-API-Key"?: string | null;
                "X-User-Id"?: string | null;
                "X-Org-Id"?: string | null;
                "X-Workspace-Id"?: string | null;
                "x-correlation-id"?: string | null;
            };
            path: {
                organization_id: string;
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
